version: "3.7"

services:
  db:
    image: postgres:13-alpine
    init: true
    restart: unless-stopped
    environment: {
      # This might seem insecure but is usually not a problem.
      # You should leave this at the "akkoma" default.
      # The DB is only reachable by containers in the same docker network,
      # and is not exposed to the open internet.
      #
      # If you do change this, remember to update "config.exs".
      POSTGRES_DB: akkoma,
      POSTGRES_USER: akkoma,
      POSTGRES_PASSWORD: akkoma,
    }
    volumes:
      - $DOCKER_DATADIR/db:/var/lib/postgresql/data
      - ./docker/initdb.sql:/docker-entrypoint-initdb.d/akkoma.sql

  server:
    build: docker/
    image: ghcr.io/hyena-network/akkoma:${AKKOMA_VERSION}
    init: true
    restart: unless-stopped
    env_file: 
      - .env
    links:
      - db
    ports: [
      # Uncomment/Change port mappings below as needed.
      # The left side is your host machine, the right one is the akkoma container.
      # You can prefix the left side with an ip.

      # Webserver (for reverse-proxies outside of docker)
      # If you use a dockerized proxy (see README), you can leave this commented
      # and use a container link instead.
      "127.0.0.1:4000:4000",

      # SSH support
      # "2222:2222",

      # Gopher support
      # "9999:9999",
    ]
    volumes:
      - ./custom.d:/custom.d:ro
      - ./docker/config.docker.exs:/home/akkoma/akkoma/config/prod.secret.exs:ro
      - ./docker/config.docker.exs:/home/akkoma/akkoma/config/dev.secret.exs:ro
      - ./emoji:/home/akkoma/akkoma/instance/static/emoji
      - ./config.d:/config.d
      - $DOCKER_DATADIR/akkoma/uploads:/uploads
      - $DOCKER_DATADIR/akkoma/secrets:/secrets
      # Uncomment for custom frontends
      #- $DOCKER_DATADIR/akkoma/frontends:/home/akkoma/akkoma/instance/static/frontends
